### ISSUE TITLE
script for visualization of taxonomies

### ISSUE THREAD

**Issue by alexanderpanchenko** [shan18/taxi#7]
**input**: 

- .taxo file (CSV / TSV)

**output**:

- .png / .svg with a visualization of an input taxonomy 

**implementation**:

- https://networkx.github.io/ 
- directed graph layouts 
- tree layout 

**use:**

- generate visualizations for all gold standard taxonomies and for all our taxonomies. 
- upload here as commments

**Comment by shan18** [comment]
![nx_test](https://user-images.githubusercontent.com/12576178/42157115-2484e576-7ded-11e8-8105-a7d1d9b51e11.png)
![nx_test1](https://user-images.githubusercontent.com/12576178/42157116-249e0074-7ded-11e8-91f7-1e3fc2993f4a.png)

The graph of the pruned taxonomy in the file **out/science_en.csv-relations.csv-taxo-knn1.csv-pruned.csv** comes out like the figures displayed above. Since there are a lot of nodes, it is difficult to read the graph by using labels.

**Comment by shan18** [comment]
![nx_test](https://user-images.githubusercontent.com/12576178/42157491-21372dec-7dee-11e8-9bdd-ef39144a209f.png)
![nx_test1](https://user-images.githubusercontent.com/12576178/42157492-215db8b8-7dee-11e8-9624-64fc7486418b.png)
This is the graph for the gold standard taxonomy. As we can see, the results obtained by the existing pruning techniques are not producing the same graph as the gold standard.

**Comment by alexanderpanchenko** [comment]
1) Try also to generate the plot avoiding the overlapping labels in the
nodes. The image may be huge in width but it is not a problem.

2) Draw the taxonomy so that the root is at the top of the tree.

**Comment by alexanderpanchenko** [comment]
You can also try the horizontal layout: root is on the left and the
children are on the right from the root. In this case you have lots of
nodes on the right. This way you also save much space - the long node
captions will take some constant space.

**Comment by shan18** [comment]
![gold](https://user-images.githubusercontent.com/12576178/42167274-d2dda02a-7e0d-11e8-9a44-43c86518384d.png)
After using the horizontal layout and enlarging the image, I am able to see this image only in jupyter notebook. My computer is not able to open this enlarged image.

**Comment by shan18** [comment]
I will also push the corresponding jupyter notebook along with the script in the repository.

**Comment by alexanderpanchenko** [comment]
Hi, this is really much-much better. Now I can see something really useful.
Yes, please push the code as well.

**Comment by alexanderpanchenko** [comment]
please generate such images for each domain for English (for the gold
standard and the automatically generated taxonomies) and put them here in
the comments as attached png files.

**Comment by shan18** [comment]
Images for the gold standard in English:

1. environment_eurovoc_en.taxo
![environment_eurovoc_en](https://user-images.githubusercontent.com/12576178/42172295-e3823932-7e1b-11e8-9a95-01862b12b892.png)

2. science_en.taxo
![science_en](https://user-images.githubusercontent.com/12576178/42172363-0cb01dce-7e1c-11e8-83c2-78b02b879b65.png)

3. science_eurovoc_en.taxo
![science_eurovoc_en](https://user-images.githubusercontent.com/12576178/42172379-1bb0ef74-7e1c-11e8-84b0-0e1d0b1618cd.png)

4. science_wordnet_en.taxo
![science_wordnet_en](https://user-images.githubusercontent.com/12576178/42172398-290e24e8-7e1c-11e8-9864-b8399f85770c.png)

I am not able to upload the **food domain** image as the resulting image is **13 MB** and the limit to attach a file in the comments is **10 MB**.

**Comment by shan18** [comment]
Images for automatically generated taxonomies (without pruning):

1. science_en.csv-relations.csv-taxo-knn1.csv
![science_en csv-relations csv-taxo-knn1](https://user-images.githubusercontent.com/12576178/42172751-33a34004-7e1d-11e8-8065-96db4f0b81fc.png)

2. science_en.csv-relations.csv-taxo-knn2.csv
![science_en csv-relations csv-taxo-knn2](https://user-images.githubusercontent.com/12576178/42172763-3f84e378-7e1d-11e8-981f-a8982174ab27.png)

The other images of the files:
3. science_en.csv-relations.csv-taxo-knn3.csv
4. science_en.csv-relations.csv-taxo-knn5.csv
5. science_en.csv-relations.csv-taxo.csv

cannot be uploaded as they are greater than 10 MB.

**Comment by alexanderpanchenko** [comment]
thanks. please use gimp to shrink it to 10mb or less.

**Comment by shan18** [comment]
After shrinking the size of the automatically generated taxonomies (without pruning):

3. science_en.csv-relations.csv-taxo-knn3.csv
![science_en csv-relations csv-taxo-knn3](https://user-images.githubusercontent.com/12576178/42213852-354f2b50-7eba-11e8-9a4b-b1ea912f5271.jpg)

4. science_en.csv-relations.csv-taxo-knn5.csv
![science_en csv-relations csv-taxo-knn5](https://user-images.githubusercontent.com/12576178/42213874-440ae9f4-7eba-11e8-89fd-02a3b215c818.jpg)

5. science_en.csv-relations.csv-taxo.csv
![science_en csv-relations csv-taxo](https://user-images.githubusercontent.com/12576178/42213899-51257672-7eba-11e8-8d3d-d452e5397721.jpg)

**Comment by shan18** [comment]
Images for the food domain gold standard in English:

![food_en](https://user-images.githubusercontent.com/12576178/42213972-83767cb6-7eba-11e8-8d64-c718ec14a5e5.jpg)

**Comment by alexanderpanchenko** [comment]
this is not needed in the readme.md

```
conda install -c anaconda networkx
$ conda install -c anaconda pygraphviz
```

just add the dependencies to the requirements.txt please

**Comment by shan18** [comment]
Installing pygraphviz requires some other dependencies to be installed. To install it with pip, I had to run,  
`sudo apt-get install python-dev graphviz libgraphviz-dev pkg-config`  
first.

But with anaconda installation, I didn't have to run any other commands. Anaconda took care of everything.

So, should I mode the modules into the requirements.txt and include the dependency installation command in README?

**Comment by alexanderpanchenko** [comment]
Ok. At least you should document the information you just wrote here :-)

**Comment by shan18** [comment]
okay

**Comment by alexanderpanchenko** [comment]
please add to the taxi web site a section with all visualized taxonomies (links to the full images)

**Comment by shan18** [comment]
Food domain generated taxonomy.

![food_en csv-relations csv-taxo-knn1](https://user-images.githubusercontent.com/12576178/42512610-56d9dfb8-8455-11e8-85b3-a18a0ca5a0c4.png)

**Comment by shan18** [comment]
## Environment Domain

*Gold Standard*
![environment_eurovoc_en](https://user-images.githubusercontent.com/12576178/42512848-e4f9786c-8455-11e8-8b8d-9be827943d83.png)

*Generated*
![environment_eurovoc_en csv-relations csv-taxo-knn1](https://user-images.githubusercontent.com/12576178/42513297-df62f53a-8456-11e8-9818-02034f6fbda6.png)
